apiVersion: v1
kind: PersistentVolume
metadata:
  name: ticket-host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/d/java-project/dh-prj/java-t/spring-cloud/config-files
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-host-pvc
spec:
  volumeName: ticket-host-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi