apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ticketservice-deploy
  labels:
    app: ts-ticketservice-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-ticketservice
  template:
    metadata:
      labels:
        app: ts-ticketservice
    spec:
      containers:
      - name: ts-ticketservice
        image: cupofjavatech/ticket-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8300
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: application-configmap
              key: TICKET_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: application-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: application-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: application-configmap
              key: SPRING_CONFIG_IMPORT
---
apiVersion: v1
kind: Service
metadata:
  name: ts-ticketservice-service
spec:
  selector:
    app: ts-ticketservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300